package jaxb;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 06:44:27 PM PST 
//




import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IndexingInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BranchNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContentMetadata">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Metadata" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="ReqInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileName",
    "indexingInfo"
})
@XmlRootElement(name = "BranchDocument")
public class BranchDocument {

    @XmlElement(name = "FileName", required = true)
    protected String fileName;
    @XmlElement(name = "IndexingInfo", required = true)
    protected BranchDocument.IndexingInfo indexingInfo;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the indexingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BranchDocument.IndexingInfo }
     *     
     */
    public BranchDocument.IndexingInfo getIndexingInfo() {
        return indexingInfo;
    }

    /**
     * Sets the value of the indexingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchDocument.IndexingInfo }
     *     
     */
    public void setIndexingInfo(BranchDocument.IndexingInfo value) {
        this.indexingInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BranchNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContentMetadata">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Metadata" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="ReqInd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "branchNo",
        "applicationName",
        "contentMetadata"
    })
    public static class IndexingInfo {

        @XmlElement(name = "BranchNo")
        protected int branchNo;
        @XmlElement(name = "ApplicationName", required = true)
        protected String applicationName;
        @XmlElement(name = "ContentMetadata", required = true)
        protected BranchDocument.IndexingInfo.ContentMetadata contentMetadata;

        /**
         * Gets the value of the branchNo property.
         * 
         */
        public int getBranchNo() {
            return branchNo;
        }

        /**
         * Sets the value of the branchNo property.
         * 
         */
        public void setBranchNo(int value) {
            this.branchNo = value;
        }

        /**
         * Gets the value of the applicationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationName() {
            return applicationName;
        }

        /**
         * Sets the value of the applicationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationName(String value) {
            this.applicationName = value;
        }

        /**
         * Gets the value of the contentMetadata property.
         * 
         * @return
         *     possible object is
         *     {@link BranchDocument.IndexingInfo.ContentMetadata }
         *     
         */
        public BranchDocument.IndexingInfo.ContentMetadata getContentMetadata() {
            return contentMetadata;
        }

        /**
         * Sets the value of the contentMetadata property.
         * 
         * @param value
         *     allowed object is
         *     {@link BranchDocument.IndexingInfo.ContentMetadata }
         *     
         */
        public void setContentMetadata(BranchDocument.IndexingInfo.ContentMetadata value) {
            this.contentMetadata = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Metadata" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="ReqInd" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "metadata"
        })
        public static class ContentMetadata {

            @XmlElement(name = "Metadata")
            protected List<BranchDocument.IndexingInfo.ContentMetadata.Metadata> metadata;

            /**
             * Gets the value of the metadata property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the metadata property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMetadata().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BranchDocument.IndexingInfo.ContentMetadata.Metadata }
             * 
             * 
             */
            public List<BranchDocument.IndexingInfo.ContentMetadata.Metadata> getMetadata() {
                if (metadata == null) {
                    metadata = new ArrayList<BranchDocument.IndexingInfo.ContentMetadata.Metadata>();
                }
                return this.metadata;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="ReqInd" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Metadata {

                /*@XmlValue
                protected String value;*/
                @XmlAttribute(name = "ReqInd")
                protected String reqInd;
                @XmlAttribute(name = "Value")
                protected String value;
                @XmlAttribute(name = "Name")
                protected String name;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 *//*
                public String getValue() {
                    return value;
                }

                *//**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 *//*
                public void setValue(String value) {
                    this.value = value;
                }*/

                /**
                 * Gets the value of the reqInd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReqInd() {
                    return reqInd;
                }

                /**
                 * Sets the value of the reqInd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReqInd(String value) {
                    this.reqInd = value;
                }

                /**
                 * Gets the value of the value1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }

    }

}
